apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "s3er.fullname" . }}-app-files
  labels:
    {{- include "s3er.labels" . | nindent 4 }}
data:
  entrypoint.sh: |
    pip install -r /app/requirements.txt
    env
    python -u /app/main.py  # -u Forces the python stdout and stderr streams to be unbuffered, to allow realtime logging from daemon container.

  requirement.txt: |
    {{- .Files.Get "s3er/requirements.txt" | nindent 4 }}

  main.py: |
    {{- .Files.Get "s3er/main.py" | nindent 4 }}

