apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "s3er.fullname" . }}
  labels:
    {{- include "s3er.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "s3er.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "s3er.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "s3er.serviceAccountName" . }}
      volumes:
      - name: app-files
        configMap:
          name: {{ include "s3er.fullname" . }}-app-files
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: BUCKET_NAME
          value: {{ quote .Values.conf.aws.eks.bucketName }}
        - name: SLEEP_SECONDS_OVERRIDE
          value: {{ quote .Values.conf.sleepSecondsOverride }}
        volumeMounts:
        - name: app-files
          mountPath: /app
        command:
        - "sh"
        - "/app/entrypoint.sh"
